version: "3"

services:
    backend:
        image: metakgporg/gyft-api
        container_name: gyft-api
        build: .
        restart: always
        networks:
            metaploy-network:
                aliases:
                    - gyft-api
        volumes:
            - nginx-config-volume:/etc/nginx/sites-enabled

networks:
    metaploy-network:
        external: true
        name: metaploy-network

volumes:
    nginx-config-volume:
        external: true
        name: metaploy-nginx-config-volume